### PR TITLE
Model Viewer

### LINKED ISSUE #1: Tetrix 3d model
This Tetrix will be replaced with [model-viewer](https://modelviewer.dev/) if possible using this model https://sketchfab.com/3d-models/sierpinski-triangle-6535bb3393b14973bc84a35c28cd886c

Feel for end user on mobile would be use gyro to rotate automatically with model :)

IP rights are solved, we've got permission from creator to use it, paying him coffee ;)

image

### PR DESCRIPTION
**Pull request by JKrupinski**
Fixes #1

### CODE REVIEW

**Comment by vikiival** [comment]
https://user-images.githubusercontent.com/22471030/143735300-0d1ad58b-11d2-4280-8b58-1f679b3a7283.MOV


The model is slightly glitched

**Comment by yangwao** [comment]
seems do nothing? 

https://user-images.githubusercontent.com/5887929/148563609-957e36bc-8959-4ac1-afda-5d8729ebb0bd.mov

**Comment by yangwao** [comment]
ah now I get it, you are working it as for future deployment! :D

**Comment by JKrupinski** [comment]
still in development, I'll finish new design first

**Pull request closed without merging**
